name: "Bugfix Workflow"
description: "Quick workflow for bug fixes - minimal overhead, maximum speed"
version: "1.0.0"

triggers:
  keywords: ["fix", "debug", "resolve", "repair", "bug"]
  complexity: ["small"]

phases:
  - id: "load-context"
    name: "Load Context"
    plugin: "ald"
    hook: "load-memory"
    required: true
    description: "Load project context"

  - id: "sprint-check"
    name: "Sprint Check"
    plugin: "ald"
    hook: "sprint-check"
    required: false
    break_on_fail: false
    description: "Check sprint scope (optional for urgent bugs)"

  - id: "find-policies"
    name: "Find Policies"
    plugin: "ald"
    hook: "policy-finder"
    required: true
    description: "Identify relevant policies"

  - id: "systematic-debugging"
    name: "Systematic Debug Analysis"
    plugin: "superpowers-dev"
    hook: "systematic-debugging"
    required: true
    description: "4-phase debugging framework: root cause → pattern → hypothesis → implementation"
    phases:
      - "root_cause_investigation"
      - "pattern_analysis"
      - "hypothesis_testing"
      - "implementation"

  - id: "root-cause-tracing"
    name: "Root Cause Tracing"
    plugin: "superpowers-dev"
    hook: "root-cause-tracing"
    required: false
    description: "Trace bugs backward through call stack to original trigger"
    when: "complex_bug_or_deep_stack"

  - id: "fix"
    name: "Apply Fix"
    plugin: "ald"
    description: "Implement bugfix following policies and systematic analysis"
    required: true
    # No specific hook - direct ALD Pre-Flight Check workflow

  - id: "defense-in-depth"
    name: "Add Defense Layers"
    plugin: "superpowers-dev"
    hook: "defense-in-depth"
    required: true
    description: "Add validation at multiple layers to prevent recurrence"
    layers:
      - "entry_point_validation"
      - "business_logic_validation"
      - "environment_guards"
      - "debug_logging"

  - id: "validate"
    name: "Quick Validation"
    plugin: "ald"
    hook: "tester"
    required: true
    description: "Validate fix works"

  - id: "review"
    name: "Quick Review"
    plugin: "ald"
    hook: "code-reviewer"
    required: false
    description: "Quick policy check"

estimated_duration: "15-30 minutes"
notes: "Enhanced with systematic debugging framework. Adds root-cause analysis and defense-in-depth validation to prevent recurrence."
