name: "Quick Feature Workflow"
description: "Medium-complexity features - planning + execution with policies"
version: "1.0.0"

triggers:
  keywords: ["implement", "create", "add"]
  complexity: ["medium"]
  has_plan: false

phases:
  - id: "load-context"
    name: "Load Context"
    plugin: "ald"
    hook: "load-memory"
    required: true

  - id: "sprint-check"
    name: "Sprint Check"
    plugin: "ald"
    hook: "sprint-check"
    required: true
    break_on_fail: true

  - id: "plan"
    name: "Quick Planning"
    plugin: "superpowers"
    hook: "write-plan"
    required: true

  - id: "find-policies"
    name: "Find Policies"
    plugin: "ald"
    hook: "policy-finder"
    required: true

  - id: "tdd-cycle"
    name: "TDD Implementation"
    plugin: "superpowers-dev"
    hook: "test-driven-development"
    required: true
    depends_on: ["plan", "find-policies"]
    description: "Execute plan with TDD Red-Green-Refactor cycle"
    cycle:
      - "RED: Write failing test for next task"
      - "Verify RED: Watch test fail correctly"
      - "GREEN: Write minimal code to pass"
      - "Verify GREEN: Watch test pass"
      - "REFACTOR: Clean up code (keep tests green)"
      - "Repeat for next task"
    rules:
      - "NO PRODUCTION CODE WITHOUT FAILING TEST FIRST"
      - "Test must fail for expected reason"
      - "Write minimal code (no over-engineering)"
      - "All tests must pass before refactor"

  - id: "defense-in-depth"
    name: "Add Validation Layers"
    plugin: "superpowers-dev"
    hook: "defense-in-depth"
    required: true
    depends_on: ["tdd-cycle"]
    description: "Add validation at multiple layers"
    layers:
      - "entry_point_validation"
      - "business_logic_validation"
      - "environment_guards"
      - "debug_logging"

  - id: "validate"
    name: "E2E Validation"
    plugin: "ald"
    hook: "tester"
    required: true
    depends_on: ["defense-in-depth"]
    retry_on_fail: true

  - id: "review"
    name: "Code Review"
    plugin: "ald"
    hook: "code-reviewer"
    required: true

estimated_duration: "30-45 minutes"
notes: "TDD by default - quick features with test-first discipline. Lighter than feature-full (no brainstorming) but same TDD quality."
